language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  edge: true
  script: poetry publish
  on:
    tags: true
    python: 3.8
env:
  global:
  - secure: "Z2a38NWAlbsfp7Ml4MBV7iyJtacDNDm6jtRpXFVZkqBgvtGFwxTBEZo9wwFGQvUt7ObFXrxdMJT7BD799ELuHWGo2UlKnDcacnPoZWvHYwF1CB3Cogt2rt+TVlt5zgXYkEbZFbHSzv/RWgfmTKtL1xJhorAUXCSGtzc2cWgltoNnO9z0XJopQr4e2+dSWd05jK30Iq66fUtcN1KG+mGBPE51gfhiDglBagyaitT3Y83wf1b2U7R0KZfIpH44h2gmFAAkQxgYPDsv1gDO5KzBYvyYozXee2B/4oQemiPhKl/0OkHNSNu5oAERzGHZCCRB3RFZF/Q6ptAWxK7rhZvuy+xBNo3nhf8JBU4RpetO/r1gA+XieD+o5BmqYErMrskS98l//sMRZV1l3qGrUnDcQTNiUa8c1xHm0ug/FKoCL5fyqy90x7NbDleGN0yq1n0fEWXypLo2YiDsD6y8FuvIJ1gGXenZFEMYzehv1g2kZSmBDChdhk5Kf91aHqVOdB55/c6i44liNZ7CrcfNLwgrQ7gx48prtLONYsLwGqku8GGTJTHyG8nsRqcF/m0IJ/akHB1eL6LI8i+UwutQaQZb0Vn15sp2wKayXbEFNW1eq3TvAjBLvXRKJvf/NSo112Cud4UnrB/gW2i5YwscMO9HXBYrEr1WinQobiOPaJvWGuY="
  - secure: "auqzQq8Wkpc5oK6hIaT8R1fBCdSfAL2OIPdCXU4zpL6uN3JCv72B7OIND8m4LcF90RvkW4w6LEbr1vZugToHUbOsGjy6sCCvdsLAC4OB+RZ1FyideozmM3Pkl2uZgbIstMtKjXdHPSrcc62zU936+utsejNAfN5Ua8/esuO/xnhQEfuFOG7WX3UgHoGKUWC60zRqTUttohRfskKlZ0gJb2qudayWj0xYeirz74xvljvdEG3mcVWX3SIiQoyvIM0DIAt2lAWaY279UXXjlllkmKGwkWQTlY3+gpe3bVyy6YiEGHTcjMqBn4pNiAofyWfhoLnD/PaKkGry1aRV28VoS1PrkzQXUlK5lbyzSrlvCAIDhm4WxXiIp4SBX2G4baObKHkaT6ggLPSsUp3aIIkbgehxLQkeV1ca2xiffRr1bR8K1Jm01DXoDRennZIySviFX0/vkJ+T+6bP74dhYKfCX1CGBbUFDIwT4jvBh8P4zotZ+Fh+KJ+/9kSS5n2vTpLMOmOA49SuQ/y/f7laQeDTJwF0VNuWModjhMLRZguOhxWTUOt/NP4j7fUJ4Wr2yyiFi97g//QQL0ghuemIcm9zy9o72Jw2IC7IAJdEf0DXFogLcyO/Yp6sScGyBJeF5iNDDv6jZWhXI4NULvy6aoYKvfKompz8jKKuI1e4o4/JLUc="
